import { inject, Injectable } from "@angular/core";
import { ReportTemplateService } from "./report-template.service";
import { UserService } from "../user.service";
import { UtilsService } from "../utils.service";
import { CustomerDetails } from "../../../interfaces/customer-details";

@Injectable({
  providedIn: "root",
})
export class CustomerDetailsService {

  private readonly userService = inject(UserService);
  private readonly utilsService = inject(UtilsService);
  private readonly templateReportGeneratorService = inject(ReportTemplateService);

  createCustomerDataSheetReport(data: CustomerDetails) {

    // Get the data of the comaker then append it on the table
    const coMakerTextEntries = data.co_makers.map((comaker) => {
      return {
        text: `${comaker.cx_detail.first_name} ${comaker.cx_detail.last_name}`,
        bold: false,
      };
    });

    // Get the data of the addresses then append it on the table
    let addressDisplayInfo = data.cx_address.map((address) => {
      return {
        text: `${address.complete_address}`,
        bold: false,
      };
    });


    this.templateReportGeneratorService.open({
      header: [
        { text: `DATE/TIME GENERATED: ${new Date().toLocaleString()}`, alignment: "right", margin: [5, 10, 5, 2], fontSize: 9 },
        { text: `GENERATED BY: ${this.userService.getFullName()}`, alignment: "right", margin: [5, 0, 5, 10], fontSize: 9, italics: true },
      ],
      content: [
        { text: "DOLBEN LENDING INVESTOR CORPORATION", fontSize: 14, color: "blue", style: "header", alignment: "center", margin: [0, 10, 0, 0] },
        { text: "16 KAUFFMAN ST., GORDON HEIGHTS, OLONGAPO CITY, ZAMBALES", style: "subtitle", alignment: "center", },
        { text: "CUSTOMER PERSONAL DATA SHEET", color: "red", bold: true, alignment: "center", fontSize: 16, margin: [0, 0, 0, 10] },
        {
          table: {
            widths: ["auto", "*"],
            body: [
              // [{ text: "ID:" }, { text: data.customer_id ?? "", bold: true }],
              [{ text: "Customer Name", bold: true }, { text: `${data.first_name ?? ""} ${data.middle_name ?? ""} ${data.last_name ?? ""} ${data.extension_name ?? ""}`, bold: false }],
              [{ text: "Sex at Birth", bold: true }, { text: data.gender.toUpperCase().replace(/_/g, " "), bold: false }],
              [{ text: "Civil Status", bold: true }, { text: data.civil_status.toUpperCase().replace(/_/g, " "), bold: false }],
              [
                { text: "Mobile Number", bold: true },
                data.mobile_number ?? "-",
              ],
              [
                { text: "Telephone Number", bold: true },
                data.telephone_number ?? "-",
              ],
              [
                { text: "Email Address", bold: true },
                data.email_address ?? "-",
              ],
              [
                { text: "Date of Birth", bold: true }, data.date_of_birth ? new Date(data.date_of_birth).toDateString() : "-",
              ],
              [{ text: "Client Status", bold: true }, data.client_status.replace(/_/g, " ") ?? "-"],

              // comaker
              [
                { text: "Co-Makers", bold: true },
                coMakerTextEntries.length > 0
                  ? { ul: coMakerTextEntries.map((item) => item.text) }
                  : "-",
              ],
              [{ text: "Co-Maker Override/Status", bold: true }, data.cmk_status ?? "-"],
              // address
              [
                { text: "Address", bold: true },
                addressDisplayInfo.length > 0
                  ? { ul: addressDisplayInfo.map((item) => item.text) }
                  : "-",
              ],
            ],
          },
          layout: "noBorders",
          style: "defaultStyle",
        }
      ],
      styles: {
        header: {
          fontSize: 12,
          bold: true,
          margin: [0, 5, 0, 5],
        },
        subtitle: {
          fontSize: 10,
          bold: false,
          margin: [0, 0, 0, 10],
        },
        defaultStyle: { margin: [0, 5, 0, 5], fontSize: 9 },
      },
      pageSize: "LETTER",
      pageOrientation: "portrait",
      watermark: { text: "DOLBEN LENDING PROPERTY", color: "red", opacity: 0.1, bold: true },
    });
  }
}